---
- name: Set hostname
  hostname:
    name: "{{ host_name }}"

- name: Add hostname in etc hosts
  lineinfile:
    dest: /etc/hosts
    line: "127.0.0.1 localhost {{ host_name }}"
    regexp: "^127.0.0.1"

- name: Install base packages
  apt:
    name: "{{item}}"
    update_cache: true
    state: latest
  with_items:
    - git
    - zsh
    - python3
    - python3-pip
    - curl
    - wget
    - vim

# Install Oh My ZSH
- name: Download install file
  get_url:
    url: https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh
    dest: /tmp
  delegate_to: localhost
  tags:
    - shell

- name: Modify user's shell
  user:
    name: "{{ ansible_ssh_user }}"
    shell: /bin/zsh
  tags:
    - shell

- name: Install ohmyzsh with script
  script: "/tmp/install.sh --unattended"
  remote_user: "{{ new_user }}"
  ignore_errors: true
  tags:
    - shell

- name: Set custom motd for RaspberryPi
  template:
    src: rpi_motd.j2
    dest: /etc/motd
  tags:
    - rpi

- name: Modify vimrc
  blockinfile:
    dest: /etc/vim/vimrc
    block: |
      syntax on
      filetype plugin indent on
      au BufNewFile,BufReadPost *.{yaml,yml} set filetype=yaml
      autocmd FileType yaml setlocal ts=2 sts=2 sw=2 expandtab
      set nocompatible
      set backspace=indent,eol,start
      au BufNewFile,BufReadPost *py set filetype=python
      autocmd FileType python setlocal ts=4 sts=4 sw=4 ff=unix
      set expandtab
      set autoindent